### PR TITLE
Create a docs folder and improve README

### PR DESCRIPTION
**Pull request by annehaley**
This PR improves the README by separating the setup and testing instructions and adding more language from the project abstract. The README is now in the docs folder, but Github will still display it on the front page of the repository. I have also added some images and a `mkdocs.yml` so we can publish this to ReadTheDocs.

Preview:
https://github.com/OpenGeoscience/uvdat/tree/update-readme

### CODE REVIEW

**Comment by johnkit** [comment]
I have some suggested editorial changes. Reorganized a bit and added a few more details. I'll attach pdf with preview as well as patch file for consideration.

[0001-Editorial-changes.patch.txt](https://github.com/OpenGeoscience/uvdat/files/13787141/0001-Editorial-changes.patch.txt)  (Remove the .txt extension -- I had to add it in order to get github to accept the upload)

[UVDAT-Documentation.pdf](https://github.com/OpenGeoscience/uvdat/files/13787134/UVDAT-Documentation.pdf)

**Comment by johnkit** [comment]
Note that if you use my changes, please fix the typo "representatitons" ==> "representations"

**Comment by johnkit** [comment]
It appears that you added `uvdat_flow.jpg` but we don't use it (commented out). Was that on purpose or just an earlier version? My preference would be to leave the image out and remove the comment (line 12 in README.md).

**Comment by annehaley** [comment]
@johnkit I added the uvdat flow diagram in [4222b7b](https://github.com/OpenGeoscience/uvdat/pull/37/commits/4222b7b52ab5d90713a822d76592bbf5fd964b08), and part of your suggested changes comments out the image reference. I removed the image and the comment in [3dbeb10](https://github.com/OpenGeoscience/uvdat/pull/37/commits/3dbeb102a3f77a454cbf1d0f92b7f5c63036ba1c).

**Review by johnkit — APPROVED** [review]
+1

**Pull request merged**
